version: '3'

services:
  back:
    build: ./back
    container_name: django
    # Para criar o projeto do zero descomente linha 8 e comente a linha 10
    # stdin_open: true
    # Para rodar o projeto descomente esta linha 10 e comente a linha 8
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /workspace
    volumes:
      - ./back/projeto/:/workspace
    restart: always
    ports:
      - "8000:8000"
    networks:
      app-network:
        ipv4_address: 11.5.0.2

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/24
          gateway: 11.5.0.1
